spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SBMS
    username: root
    password: Bhaskar@71
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
